ifneq (,$(filter tinydtls,$(USEPKG)))
  USEMODULE += tinydtls
  USEMODULE += tinydtls_contrib
  USEMODULE += event_callback
endif

ifneq (,$(filter tinydtls,$(USEMODULE)))
  USEMODULE += memarray
  USEMODULE += hashes
  USEMODULE += tinydtls_aes
  USEMODULE += tinydtls_ecc
endif
